version: '2'
services:
  rabbit:
    image: rabbitmq:3.6-management
    ports:
     - "8080:15672"
     - "5672:5672"

  golang:
    build: golang
    environment:
      - twitterConsumerKey
      - twitterConsumerSecret
      - twitterAccessToken
      - twitterTokenSecret
    depends_on:
      - rabbit
