version: '2.1'
services:
  rabbit:
    build:
      context: .
      dockerfile: rabbitdockerfile
    ports:
     - "8080:15672"
     - "5672:5672"
    healthcheck:
      test: curl -f http://localhost:15672
      interval: 15s
      timeout: 3s
      retries: 10

  golang:
    image: dc17demostep03addgolang_dc2017golangapp
    environment:
      - twitterConsumerKey
      - twitterConsumerSecret
      - twitterAccessToken
      - twitterTokenSecret
    depends_on:
      rabbit:
        condition: service_healthy

  datadog:
    image: datadog/docker-dd-agent:latest
    environment:
      - API_KEY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - ./datadog-conf:/conf.d:ro
      - /proc:/host/proc:ro
    links:
      - rabbit
      - golang