version: '2'
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
     - "8080:15672"
     - "5672:5672"

  dc2016golangapp:
    image: dc16demostep03addgolang_dc2016golangapp
    environment:
      - twitterConsumerKey
      - twitterConsumerSecret
      - twitterAccessToken
      - twitterTokenSecret
    depends_on:
      - rabbit

