version: '2.1'
services:
  rabbit:
    build:
      context: .
      dockerfile: rabbitdockerfile
    ports:
     - "8080:15672"
     - "5672:5672"
    healthcheck:
      test: curl -f http://localhost:15672
      interval: 15s
      timeout: 3s
      retries: 10

  golangapp:
    build: golang
    environment:
      - twitterConsumerKey
      - twitterConsumerSecret
      - twitterAccessToken
      - twitterTokenSecret
    links:
      - rabbit
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:8123
      interval: 30s
      timeout: 3s
      retries: 10

  logstash:
    build: logstash
    command: -f /etc/logstash.conf
    depends_on:
      golangapp:
        condition: service_healthy


  datadog:
    image: datadog/docker-dd-agent:latest
    environment:
      - API_KEY
    ports:
      - "8125:8125"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - ./datadog-conf:/conf.d:ro
      - /proc:/host/proc:ro
